"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Seb00927 (https://sketchfab.com/Seb00927)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/book-lowpoly-27aa99343cc8467c8bb7e462d7963ae8
Title: Book (LowPoly)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/bgnotes/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" scale={1.7} rotation={[0, 0, -Math.PI / 2]} position={[0,0,0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Hoja_5" position={[0, 0.057, 0.56]} rotation={[-0.262, 0, 0]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Paper} />
              </group>
              <group name="Book_Right_2" position={[0, 0.015, 0]} rotation={[2.88, 0, Math.PI]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Cover} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Paper} />
              </group>
              <group name="Line_in_the_middle_3" position={[0, -0.097, 0]} scale={[0.949, 0.01, 0.01]}>
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Black} />
              </group>
              <group name="Book_Left_4" position={[0, 0.015, 0]} rotation={[2.88, 0, Math.PI]}>
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Cover} />
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Paper} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bgnotes/scene.gltf')
